name: Publish

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: NPM Install, build and test
        run: |
          npm install
          npm run eslint
          npm run test
          npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build and Deploy to Storybook
        run: |
          npm run storybook:build
          npm run storybook:deploy
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        plugins:
        - "@semantic-release/github":
            githubUrl: "https://github.com/takenet/blip-ds"
            githubApiPathPrefix: /api/v3/
            failComment: false
            
        with:
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
